import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { DATA } from "@/data/resume";
import { cn } from "@/lib/utils";
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FlickeringGrid } from "@/components/magicui/flickering-grid";
import { JsonLd } from "@/components/json-ld";

// Centralised, intent-grouped keyword set. Grouping (role → stack → cloud → AI →
// location → brand) keeps the list keyword-RICH but semantically coherent, which
// helps traditional crawlers and AI answer engines understand relevance without
// tripping keyword-stuffing heuristics.
const KEYWORDS = [
  // Primary role / positioning
  "Senior Full Stack Engineer",
  "Senior React Developer",
  "React Developer",
  "Next.js Developer",
  "Node.js Developer",
  "TypeScript Developer",
  "JavaScript Developer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Developer",
  "Software Engineer",
  "Web Developer",
  "Enterprise Software Engineer",
  "React Consultant",
  "Next.js Consultant",
  // Secondary stack & platform
  "AWS Developer",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ruby on Rails",
  "PostgreSQL",
  "REST API",
  "GraphQL",
  "Cloud Engineer",
  "CI/CD",
  "Redis",
  "Performance Optimization",
  "Frontend Architecture",
  "Backend Architecture",
  "Scalable Web Applications",
  // AI / data engineering
  "AI Engineer",
  "Agentic AI",
  "LLM Engineer",
  "OpenAI",
  "LangChain",
  "AI Automation",
  "AI Applications",
  "Generative AI",
  "Data Engineering",
  "Python Developer",
  // Location & availability
  "Full Stack Developer Pakistan",
  "React Developer Pakistan",
  "Next.js Developer Pakistan",
  "Remote React Developer",
  "Remote Full Stack Engineer",
  "Remote Software Engineer",
  // Personal brand
  "Syed Muhammad Abid",
  "Syed Muhammad Abid Hussain",
  "syedmuhammadabid.dev",
];

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  // metadataBase makes every relative URL below (Open Graph images, canonical,
  // etc.) resolve to an absolute production URL, which social + AI crawlers require.
  metadataBase: new URL(DATA.url),
  title: {
    // Keyword-led default title for the home document.
    default: `${DATA.name} — ${DATA.jobTitle} | React, Next.js & Node.js`,
    // Child routes render as "Page Title | Syed Muhammad Abid".
    template: `%s | ${DATA.name}`,
  },
  description: DATA.description,
  // Broad but coherent keyword set (see KEYWORDS above).
  keywords: KEYWORDS,
  // Authorship / publisher signals used by search engines and AI attribution.
  authors: [{ name: DATA.fullName, url: DATA.url }],
  creator: DATA.fullName,
  publisher: DATA.fullName,
  applicationName: `${DATA.name} Portfolio`,
  category: "technology",
  // Self-referencing canonical for the home route prevents duplicate-content
  // dilution (e.g. www vs non-www, trailing slash, query params).
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: `${DATA.name} — ${DATA.jobTitle}`,
    description: DATA.description,
    url: DATA.url,
    siteName: `${DATA.name}`,
    locale: "en_US",
    type: "website",
    // Image is generated by app/opengraph-image.tsx and injected automatically;
    // no manual og:image entry needed.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    card: "summary_large_image",
    title: `${DATA.name} — ${DATA.jobTitle}`,
    description: DATA.description,
    creator: "@syedmuhammadabid",
  },
  // Favicons / app icons. app/icon.svg is auto-detected by Next; declaring it
  // explicitly also wires up the shortcut + Apple touch icon.
  icons: {
    icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
    shortcut: ["/icon.svg"],
    apple: [{ url: "/icon.svg" }],
  },
  // Links the generated PWA manifest (app/manifest.ts).
  manifest: "/manifest.webmanifest",
  verification: {
    google: "",
    yandex: "",
  },
};

// Viewport + theme-color live in the dedicated `viewport` export per the Next.js
// App Router Metadata API (they are no longer valid inside `metadata`).
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Adaptive browser UI colour that matches the light/dark backgrounds.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#121212" },
  ],
  colorScheme: "light dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Site-wide structured data (Person + WebSite + ProfilePage) so search
            engines and AI answer engines can build a rich entity for the brand. */}
        <JsonLd />
        {/* Speed up the first connection to Google Fonts (used by next/font) and
            the GitHub asset host used for project media/avatars. */}
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://raw.githubusercontent.com"
          crossOrigin="anonymous"
        />
        <link rel="dns-prefetch" href="https://raw.githubusercontent.com" />
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased relative",
          geist.variable,
          geistMono.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TooltipProvider delayDuration={0}>
            <div className="absolute inset-0 top-0 left-0 right-0 h-[100px] overflow-hidden z-0">
              <FlickeringGrid
                className="h-full w-full"
                squareSize={2}
                gridGap={2}
                style={{
                  maskImage: "linear-gradient(to bottom, black, transparent)",
                  WebkitMaskImage: "linear-gradient(to bottom, black, transparent)",
                }}
              />
            </div>
            <div className="relative z-10 max-w-2xl mx-auto py-12 pb-24 sm:py-24 px-6">
              {children}
            </div>
            <Navbar />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
